package org.gdufs.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StudentDaoDelegate", targetNamespace = "http://service.gdufs.org/")
public interface StudentDaoDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns org.gdufs.service.Student
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findStudentById", targetNamespace = "http://service.gdufs.org/", className = "org.gdufs.service.FindStudentById")
	@ResponseWrapper(localName = "findStudentByIdResponse", targetNamespace = "http://service.gdufs.org/", className = "org.gdufs.service.FindStudentByIdResponse")
	public Student findStudentById(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
